### ISSUE TITLE
Cannot use with ReSharper 2019.2.2 

### ISSUE THREAD

**Issue by mu88** [matkoch/resharper-testlinker#16]
I'm using ReSharper 2019.2.2 in Visual Studio 2019 (16.3). After installing this extension, neither does *Go to related files* provide a link to the test code nor is there an entry called *Test Linker* within the ReSharper Options.

**Comment by mu88** [comment]
Do you have any clue what might be wrong?

**Comment by matkoch** [comment]
Can you try starting resharper in internal mode? This will indicate exceptions in the statusbar.

**Comment by mu88** [comment]
There is the following exception:
```
Line number must be below the number of lines, 74. Parameter name: line Actual value was 80.

--- EXCEPTION #1/2 [ArgumentOutOfRangeException]
Message = “Line number must be below the number of lines, 74.”
ExceptionPath = Root.InnerException
ClassName = System.ArgumentOutOfRangeException
Data.ThreadLocalDebugInfo = BreakpointsBrowserDescriptor.InitDataFlow
HResult = COR_E_ARGUMENTOUTOFRANGE=80131502
Source = JetBrains.Platform.DocumentModel
ParamName = line
ActualValue = 80
StackTraceString = “
  at JetBrains.DocumentModel.Impl.LineIndex.GetLineEndOffsetNoLineBreak(Int32`1 line)
     at JetBrains.DocumentModel.Impl.DocumentBase.GetLineLength(Int32`1 line)
     at JetBrains.ReSharper.Feature.Services.DebuggerVs.BreakpointOccurrence..ctor(ISolution solution, IVsBreakpointWrapper breakpoint)
     at JetBrains.PsiFeatures.VisualStudio.Debugger.Breakpoints.BreakpointsBrowserDescriptor.<>c__DisplayClass24_0.<InitDataFlow>b__0(AddRemoveIndexEventArgs`1 args)
     at JetBrains.DataFlow.ListEvents`1.OnAcknowledgeSinkAddRemove_Add(Action`1 handler)
”

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]
Message = “
  Line number must be below the number of lines, 74.
  Parameter name: line
  Actual value was 80.
”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
Data.ManagedThreadName = <NULL>
Data.LastExtension = cs
Data.SccRevisionShell = “<there are no packages matching the criteria>”
Data.HostProductInfo = “JetBrains ReSharper Ultimate 2019.2.2 Build 192.0.20190828.114715”
Data.SubProducts.#0 = “JetBrains dotCover 2019.2.2 Build 2019.2.20190828.152744”
Data.SubProducts.#1 = “JetBrains dotTrace 2019.2.2 Build 2019.2.20190828.153049”
Data.SubProducts.#2 = “JetBrains ReSharper 2019.2.2 Build 2019.2.20190828.152259”
Data.SubProducts.#3 = “JetBrains dotMemory 2019.2.2 Build 2019.2.20190828.152855”
Data.SccRevisionEnv = “
  Platform\Core\Shell:
  	git::refs/heads/192-eap9-rtm-2019.2.2
  
  Platform\VisualStudio:
  	git::refs/heads/192-eap9-rtm-2019.2.2::823e95ab978831bb278c7c454ef595a21c48686e
”
Data.VsVersion = 16.3.29409.12
InnerException = “Exception #1 at Root.InnerException”
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  at JetBrains.DataFlow.ListEvents`1.OnAcknowledgeSinkAddRemove_Add(Action`1 handler)
     at JetBrains.DataFlow.Infra.SignalWithDelegates`1.OnAfterAdvise(Action`1 handler)
     at JetBrains.DataFlow.Signal`1.<>c__DisplayClass19_0.<AdviseCore>b__0()
     at JetBrains.Lifetimes.LifetimeDefinition.Bracket(Action opening, Action closing)
     at JetBrains.DataFlow.Signal`1.AdviseCore(Action`1 handler, Lifetime lifetime)
     at JetBrains.DataFlow.Signal`1.Advise(Lifetime lifetime, Action`1 handler)
     at JetBrains.PsiFeatures.VisualStudio.Debugger.Breakpoints.BreakpointsBrowserDescriptor.InitDataFlow(ISolution solution, Lifetime lifetime, NoContentLockInsideReadWriteLock rwlock)
     at JetBrains.PsiFeatures.VisualStudio.Debugger.Breakpoints.BreakpointsBrowserDescriptor.<>c__DisplayClass20_2.<.ctor>b__3()
     at JetBrains.Application.Threading.IShellLocksEx.ExecuteWithReadLock(IShellLocks thіs, Action F)
     at JetBrains.Application.Threading.IShellLocksEx.<>c__DisplayClass5_0.<ExecuteOrQueueReadLock>b__0()
     at JetBrains.Threading.ReentrancyGuardEx.<>c__DisplayClass0_1.<Queue>b__3()
     at JetBrains.Threading.ReentrancyGuard.Execute(String name, Action action)
     at JetBrains.Threading.ReentrancyGuard.ExecutePendingActions()
     at JetBrains.Threading.JetDispatcher.Closure.Execute()
     at JetBrains.Util.Concurrency.WinJetDispatcher.ProcessQueue(Int32 nMinBucket)
     at JetBrains.Util.Concurrency.WinJetDispatcher.<>c__DisplayClass18_0.<BeginInvokeCore>b__0()
     at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
     at System.Windows.Threading.DispatcherOperation.InvokeImpl()
     at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
     at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Windows.Threading.DispatcherOperation.Invoke()
     at System.Windows.Threading.Dispatcher.ProcessQueue()
     at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
     at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
     at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
     at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
     at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
”

```

And the second one:
```
There are 2 option pages with the same ID “General”.

--- EXCEPTION #1/2 [InvalidOperationException]
Message = “There are 2 option pages with the same ID “General”.”
ExceptionPath = Root.InnerException
ClassName = System.InvalidOperationException
HResult = COR_E_INVALIDOPERATION=80131509

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]
Message = “There are 2 option pages with the same ID “General”.”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
Data.ManagedThreadName = <NULL>
Data.SccRevisionShell = “<there are no packages matching the criteria>”
Data.HostProductInfo = “JetBrains ReSharper Ultimate 2019.2.2 Build 192.0.20190828.114715”
Data.SubProducts.#0 = “JetBrains dotCover 2019.2.2 Build 2019.2.20190828.152744”
Data.SubProducts.#1 = “JetBrains dotTrace 2019.2.2 Build 2019.2.20190828.153049”
Data.SubProducts.#2 = “JetBrains ReSharper 2019.2.2 Build 2019.2.20190828.152259”
Data.SubProducts.#3 = “JetBrains dotMemory 2019.2.2 Build 2019.2.20190828.152855”
Data.SccRevisionEnv = “
  Platform\Core\Shell:
  	git::refs/heads/192-eap9-rtm-2019.2.2
  
  Platform\VisualStudio:
  	git::refs/heads/192-eap9-rtm-2019.2.2::823e95ab978831bb278c7c454ef595a21c48686e
”
Data.VsVersion = 16.3.29409.12
InnerException = “Exception #1 at Root.InnerException”
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  at JetBrains.Application.UI.Options.OptionPagesTree.<>c.<Init_MapIdToEntity>b__3_2(IGrouping`2 duplicate)
     at JetBrains.Util.CollectionUtil.ForEach[T](IEnumerable`1 collection, Action`1 action)
     at JetBrains.Application.UI.Options.OptionPagesTree.Init_MapIdToEntity(IEnumerable`1 optionpages)
     at JetBrains.Application.UI.Options.OptionPagesTree..ctor(IEnumerable`1 optionpages, OptionPagesDiagnostics diagnostics)
     at JetBrains.Application.UI.Options.OptionsDialog.OptionsModel..ctor(Lifetime lifetime, ISettingsStore settingsStore, IOptionPagesList optionpages, IComponentContainer containerForPageViews, IThreading threading, ILogger logger, OptionPagesDiagnostics diagnostics, OptionsSessionDefinition sessionDefinition, IViewable`1 customLayerProviders)
     at JetBrains.Application.UI.Options.OptionsDialog.OptionsDialogModel..ctor(Lifetime lifetime, ISettingsStore settingsStore, IOptionPagesList optionpages, IComponentContainer containerForPageViews, HelpSystem helpSystem, ILogger logger, IActionManager actionman, IThreading threading, OptionPagesDiagnostics diagnostics, OptionsSessionDefinition sessionDefinition, IViewable`1 customLayerProviders)
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at JetBrains.Application.Components.SingletonTypeComponentDescriptor.CreateInstanceOf(Type type, IValueResolveContext context)
     at JetBrains.Application.Components.SingletonTypeComponentDescriptor.CreateInstance(IValueResolveContext context)
     at JetBrains.Application.Components.SingletonDescriptor.CreateInstanceChecked(OnError onError, IComponentContainer container)
     at JetBrains.Application.Components.SingletonDescriptor.GetValue()
     at JetBrains.Application.Components.InitializationStrategyDefault.Schedule(Lifetime lifetime, ICollection`1 dscs, IComponentContainer container)
     at JetBrains.Application.Components.ComponentStorage.ComposeDescriptors(ICollection`1 descriptors)
     at JetBrains.Application.Components.ComponentStorage.Compose()
     at JetBrains.UI.Options.OptionPages.OptionsDialogViewOwnerInteractive.<>c__DisplayClass1_0.<.ctor>b__0(OptionsSessionDefinition session, IWin32Window win32owner)
     at JetBrains.UI.Options.OptionPages.OptionsDialogViewOwnerInteractive.<>c__DisplayClass1_2.<.ctor>b__3(LifetimeDefinition definition, IWin32Window owner)
     at JetBrains.UI.StdApplicationUI.ShowDialogs.<>c__DisplayClass4_0.<ShowDialogWithGuardedCreation>b__0(LifetimeDefinition ltdef, IWin32Window owner)
     at JetBrains.UI.Extensions.WindowUtil.<>c__DisplayClass16_2.<ShowDialogWithGuardedCreation>b__6(LifetimeDefinition def)
     at JetBrains.Threading.ReentrancyGuard.Execute[TState,TResult](String name, TState state, Func`2 func)
     at JetBrains.UI.Extensions.WindowUtil.ShowDialogWithGuardedCreation(Lifetime lifetime, WindowModality modality, IThreading threading, IApplicationModalState applicationModalState, Func`3 FCreateView, Func`1 FGetOwner)
     at JetBrains.UI.Extensions.WindowUtil.<>c__DisplayClass16_0.<ShowDialogWithGuardedCreation>b__1()
     at JetBrains.Util.Logging.Logger.Catch(Action action)
     at JetBrains.Application.Threading.IThreadingEx.<>c__DisplayClass18_1.<ExecuteOrQueueWhenNotGuarded>b__4()
     at JetBrains.Threading.JetDispatcher.Closure.Execute()
     at JetBrains.Util.Concurrency.WinJetDispatcher.ProcessQueue(Int32 nMinBucket)
     at JetBrains.Util.Concurrency.WinJetDispatcher.<>c__DisplayClass18_0.<BeginInvokeCore>b__0()
     at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
     at System.Windows.Threading.DispatcherOperation.InvokeImpl()
     at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
     at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Windows.Threading.DispatcherOperation.Invoke()
     at System.Windows.Threading.Dispatcher.ProcessQueue()
     at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
     at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
     at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
     at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
     at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
”

```

**Comment by mu88** [comment]
Do you have any further ideas?

**Comment by mu88** [comment]
I'd like to ask whether there are some news regarding this issue?

**Comment by matkoch** [comment]
I can probably give you an update next week, when the new EAP5 is out. Previously, it seemed that there was a duplicated ID, which is out of my ability to change from the plugin.

**Comment by Mike-E-angelo** [comment]
Happy New Year. 🎉

I installed this for `2019.3.1` but do not see the keyboard shortcuts nor do I see this in options.  Same issue?

![](https://i.imgur.com/W11YMna.png)

---

Please vote to improve the extension model experience so we don't have to continually nag extension authors for each release:

https://youtrack.jetbrains.com/issue/RSRP-459966

**Comment by Mike-E-angelo** [comment]
Do I have something installed incorrectly, perhaps?  This extension is available and can be installed, but it is as if it is not there when looking through expected features.

**Comment by matkoch** [comment]
Should work again with `2019.3.1`. Although you won't see a dedicated options page. It was merged with the _General_ options page for _Unit Testing_.

**Comment by Mike-E-angelo** [comment]
Woohoo!  Thank you for the clarification, @matkoch!  To make matters worse, it appears I searched for "related" and not "linked" in the keyboard shortcuts so I was under the impression those were gone, too.  I was able to get the binding with the correct search and can confirm it works now. 👍
