### ISSUE TITLE
Dialog to Create Class, But No Class

### ISSUE THREAD

**Issue by Mike-E-angelo** [matkoch/resharper-testlinker#17]
Using this commit:

https://github.com/DragonSpark/Framework/tree/fbcea5605a9f884276d73dc037924e97c4dea683

And in this directory:

https://github.com/DragonSpark/Framework/tree/fbcea5605a9f884276d73dc037924e97c4dea683/DragonSpark

I create a simple class called `Class1`.  I get the dialog:

![](https://i.imgur.com/ppsKo48.png)

So far, so good.

However, when accepting and clicking `Yes`, the test file does not seem to create in the specified namespace/folder, or at all.

I know that in #16 it was mentioned options were merged, but I am not seeing anything obvious... is there another setting somewhere I should be considering, perhaps?

**Comment by matkoch** [comment]
What setting are you looking for? The only settings that are being added
are regarding navigation patterns. And they should appear on Unit Testing
General.

**Comment by Mike-E-angelo** [comment]
I'm looking for the setting that will create the test as the dialog suggests it will do. :)

FWIW if the file already exists I navigate to it as expected.  It's basically the creating of files that is not working.

**Comment by matkoch** [comment]
Well there’s certainly no setting to enable or disable bugs 🤔

**Comment by Mike-E-angelo** [comment]
> Well there’s certainly no setting to enable or disable bugs 

YET. 😅

**Comment by Mike-E-angelo** [comment]
Is this project considered broken, then? 😞  It's obviously frustrating that it worked perfectly fine in previous versions but because of the upgrade path ReSharper forces extensions, it has somehow introduced a breaking change here.

Kind reminder to vote:

https://youtrack.jetbrains.com/issue/RSRP-459966

**Comment by matkoch** [comment]
@Mike-EEE I'm sorry. This has a much lower priority than anything else, and I haven't had any time to look into that :( I will try this week, but without any promises :/

**Comment by Mike-E-angelo** [comment]
No worries @matkoch I'm trying to balance my nags with perspective. 😆  

Good thing that the rest of R# is so ridiculously awesome or else this would be a bigger deal than it is. 😁

**Comment by Mike-E-angelo** [comment]
This seems to have actually progressed somehow.  I have created a simple repo here:

https://github.com/Mike-EEE/TestLinker.Basic.git

Opening this file and invoking `ReSharper_GotoLinkedTypesAction` results in the following dialog for me:

![](https://i.imgur.com/qTVuZkz.png)

Here are my options:

![](https://i.imgur.com/4JpUKGB.png)

Please let me know if you are able to reproduce this and/or if you require further logging on my side AND/OR if there is something completely obvious here I am overlooking. 😁

**Comment by matkoch** [comment]
An empty repo?

**Comment by Mike-E-angelo** [comment]
😭😭😭

Hey, you all aren't the only ones that are buggy.

😆😆😆

Try now.

😁😁😁

**Comment by matkoch** [comment]
Just looking at the code, this is completely natural to me. There is no
matching pair of implementation/test in the solution. So it can’t infer
where to put tests.

**Comment by Mike-E-angelo** [comment]
Alright, I have stepped into the Twilight Zone here.  Why is `TestLinker.Testing` not considered?

**Comment by matkoch** [comment]
I’m talking about a pair of implementation and test classes. This seemed to
be the most efficient approach.

**Comment by Mike-E-angelo** [comment]
You've lost me, unfortunately.  From the top. 😁  I am attempting to create a test class from utilizing `ReSharper_GotoLinkedTypesAction` in a code file  (`Class1.cs`) which historically finds the test project (`TestLinker.Testing`) and creates a test class (`Class1Tests.cs`).  It is now producing the dialog presented above instead.  What do I have misunderstood here?

**Comment by matkoch** [comment]
The plugin doesn’t work if there is not at least a single known pair of
implementation and test class. This is the case in the repository you’ve
created. Add, for instance, Class.cs and ClassTests.cs with according
classes, and it would work for the next pair.

**Comment by matkoch** [comment]
This is expected behavior. It always worked like that.

**Comment by Mike-E-angelo** [comment]
OK!  I am with you now.  Previously I have always had at least one "paired connection" so that I never had to create one, so that explains that.

Now, for this solution, if you link the `Class1` by creating a `Class1Tests` in `TestLinker.Testing`, and then create a `Class2`, invoke `ReSharper_GotoLinkedTypesAction` on `Class2` does it create `Class2Tests` ?  It does not for me and I can get some logs for you if needed.

**Comment by matkoch** [comment]
That should be working like that, yes.

**Comment by Mike-E-angelo** [comment]
I know it _should_ be working like that. 😁  But I am asking you if it _does_ work like that on your side.

FWIW I added it here to try:

https://github.com/Mike-EEE/TestLinker.Basic/blob/master/TestLinker/Class2.cs

**Comment by Mike-E-angelo** [comment]
Capture of what I am seeing I PROMISE I AM NOT MAKING THIS UP. 😅

https://i.imgur.com/HvqclhO.gifv

**Comment by Mike-E-angelo** [comment]
Alright, I've created logs and sent it to you JB email account.  Please let me know if you require any further/additional information to further diagnose this issue. 👍

**Comment by matkoch** [comment]
Have you started devenv.exe with /Resharper.Internal? Any exception shown
in the statusbar?

**Comment by Mike-E-angelo** [comment]
I did and sent you the logs per above... did you receive them?

Are you saying that you cannot reproduce this on your side with the provided SLN?

**Comment by Mike-E-angelo** [comment]
Ah apologies @matkoch ... details.  The configuration I had was for logging only and not `/Resharper.Internal`.  I now have _two_ ReSharper Visual Studio shortcuts on my desktop. :)

This is what is produced:

```
This action cannot be executed on the UiTaskExecutorWorker:114 thread. It's only allowed to run on the :1 thread.

--- EXCEPTION #1/2 [ThreadAccessException]
Message = “This action cannot be executed on the UiTaskExecutorWorker:114 thread. It's only allowed to run on the :1 thread.”
ExceptionPath = Root.InnerException
ClassName = JetBrains.Threading.ThreadAccessException
HResult = COR_E_APPLICATION=80131600
Source = JetBrains.Platform.Core
StackTraceString = “
  at JetBrains.Threading.JetDispatcher.AssertAccess()
     at JetBrains.DocumentModel.Transactions.DocumentTransactionManager.StartTransaction(String commandName, Boolean optimizeChangesOnCommit)
     at JetBrains.DocumentModel.Transactions.DocumentTransactionCookie..ctor(DocumentTransactionManager manager, DefaultAction defaultAction, String commandName, Boolean optimizeChangesOnCommit, IUndoRedoHandler undoRedoHandler, IProgressIndicator pi)
     at JetBrains.DocumentManagers.Transactions.ProjectModelTransactionFactory.CreateTransactionCookie(DefaultAction defaultAction, String commandName, IUndoRedoHandler handler, Boolean optimizeChangesOnCommit, IProgressIndicator pi)
     at JetBrains.DocumentManagers.impl.ProjectFileUtil.GetOrCreateProjectFolder(IProjectFolder baseFolder, FileSystemPath path, IProjectModelTransactionCookie cookie, IFolderCreationContext context)
     at ReSharperPlugin.TestLinker.Utils.ModificationUtility.GetLinkedTypeFolder(String linkedTypeNamespace, IProject linkedTypeProject)
     at ReSharperPlugin.TestLinker.Utils.ModificationUtility.TryCreateTestOrProductionClass(ITypeElement sourceType, ITextControl textControl)
     at ReSharperPlugin.TestLinker.Navigation.LinkedTypesSearchRequest.Search(IProgressIndicator progressIndicator)
     at JetBrains.ReSharper.Feature.Services.Navigation.Requests.SearchRequest.<>c__DisplayClass9_1.<Search>b__1()
     at JetBrains.Application.Threading.IShellLocksEx.ExecuteWithReadLock(IShellLocks thіs, Action F)
     at JetBrains.ReSharper.Feature.Services.Navigation.Requests.SearchRequest.<>c__DisplayClass9_0.<Search>b__0(IProgressIndicator pro)
     at JetBrains.UI.SrcView.Progress.UITaskExecutorRun.RunStartTaskCallTaskAction(IProperty`1 isDone, ProgressIndicator progressIndicator, TaskThreadAffinity taskThreadAffinity, Action`1 FTask, JetDispatcher dispatcherPrimary)
”

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]
Message = “This action cannot be executed on the UiTaskExecutorWorker:114 thread. It's only allowed to run on the :1 thread.”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
Data.ManagedThreadName = UiTaskExecutorWorker
Data.LastExtension = cs
Data.SccRevisionShell = “<there are no packages matching the criteria>”
Data.HostProductInfo = “JetBrains ReSharper Ultimate 2019.3.2 Build 193.0.20200209.70108”
Data.SubProducts.#0 = “JetBrains dotCover 2019.3.2 Build 2019.3.20200209.94935”
Data.SubProducts.#1 = “JetBrains dotTrace 2019.3.2 Build 2019.3.20200209.94927”
Data.SubProducts.#2 = “JetBrains ReSharper 2019.3.2 Build 2019.3.20200209.72252”
Data.SubProducts.#3 = “JetBrains dotMemory 2019.3.2 Build 2019.3.20200209.94942”
Data.SccRevisionEnv = “
  Platform\Core\Shell,
  Platform\VisualStudio:
  	git::refs/heads/net193-eap8-rtm-2019.3.2
”
Data.VsVersion = 16.4.29806.167
InnerException = “Exception #1 at Root.InnerException”
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  at JetBrains.UI.SrcView.Progress.UITaskExecutorRun.RunStartTaskCallTaskAction(IProperty`1 isDone, ProgressIndicator progressIndicator, TaskThreadAffinity taskThreadAffinity, Action`1 FTask, JetDispatcher dispatcherPrimary)
     at JetBrains.UI.SrcView.Progress.UITaskExecutorRun.<>c__DisplayClass11_0.<RunStartTask>b__0()
     at JetBrains.Threading.JetDispatcher.Closure.Execute()
     at JetBrains.Util.Concurrency.WinJetDispatcher.ProcessQueue(Int32 nMinBucket)
     at JetBrains.Util.Concurrency.WinJetDispatcher.<>c__DisplayClass18_0.<BeginInvokeCore>b__0()
     at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
     at System.Windows.Threading.DispatcherOperation.InvokeImpl()
     at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
     at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Windows.Threading.DispatcherOperation.Invoke()
     at System.Windows.Threading.Dispatcher.ProcessQueue()
     at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
     at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
     at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
     at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
     at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
     at JetBrains.Interop.WinApi.User32Dll.DispatchMessageW(MSG* lpmsg)
     at JetBrains.Util.Concurrency.WinJetDispatcher.WinJetDispatcherStaticMethods.InternalPumpMessagesOnce()
     at JetBrains.Util.Concurrency.WinJetDispatcher.WinJetDispatcherStaticMethods.JetBrains.Util.Concurrency.IJetDispatcherStaticMethods.Run()
     at JetBrains.Threading.JetDispatcher.<>c__DisplayClass22_1.<CreateDispatcherThread>b__1()
     at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.ThreadHelper.ThreadStart()
”

```

**Comment by Mike-E-angelo** [comment]
Also reported here: https://youtrack.jetbrains.com/issue/DEXP-499061

**Comment by Mike-E-angelo** [comment]
Now that we got that sorted. 😁  What are your thoughts on this @matkoch?  Big deal or nah?  😇

**Comment by Mike-E-angelo** [comment]
I just installed `2019.3.3` with the slight hope that perhaps something somewhere was adjusted somehow and someway to address this issue but the problem still happens. 😭😭😭  

Keep in mind that I get a not-so-subtle reminder of this issue whenever I create a new class and want to create a test for it so I am passing the savings (read: pain 😏) onto you. 😁😁😁

And I am currently full throttle into designing new classes/modelling for my project right now.

😞😞😞

---

Kind reminder to vote for this issue here:

https://youtrack.jetbrains.com/issue/RSRP-459966

---

(Thinking it would be quite the accomplishment to nag JB so much on this issue their own developers start voting for it. 😆)

**Comment by Mike-E-angelo** [comment]
This looks to be working now in the private link you sent me @matkoch.  THANK YOU SO MUCH!  It would be great to get this posted to a preview feed or in the actual public release feed itself.  Thank you once again for your efforts and patience in fixing this issue!

**Comment by Mike-E-angelo** [comment]
In case anyone else is interested in these links until they are posted in an official capacity on a feed:

`2019.3.2`+ version:
https://www.dropbox.com/s/dn8m3c3t8aliirg/ReSharper.TestLinker.2019.3.2.nupkg?dl=0

`2020.1 EAP` version:
https://www.dropbox.com/s/t6gfavbcgkwqyl3/ReSharper.TestLinker.2020.1.0.nupkg?dl=0
