### ISSUE TITLE
Rename refactoring no longer works after installing TestLinker 1.3.1 in R# 2016.3.2

### ISSUE THREAD

**Issue by fschmied** [matkoch/resharper-testlinker#3]
This seems to be caused by a number of `FileLoadExceptions` thrown by TestLinker when it tries to load NuGet.Core version 2.13.0.824, but the version found is 2.14.0.832.

From ReSharper's exception dialog:

```
The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

--- EXCEPTION #1/2 [FileLoadException]
Message = “The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)”
ExceptionPath = Root.InnerException
ClassName = System.IO.FileLoadException
HResult = FUSION_E_REF_DEF_MISMATCH=80131040
Source = TestLinker
StackTraceString = “
  at TestLinker.Caching.LinkedNamesCache.RemoveData(IPsiSourceFile sourceFile)
     at TestLinker.Caching.LinkedNamesCache.Merge(IPsiSourceFile sourceFile, Object builtPart)
     at JetBrains.ReSharper.Psi.Caches.SimpleICache`1.ProcessDirty()
     at JetBrains.ReSharper.Psi.Caches.SimpleICache`1.SyncUpdate(Boolean underTransaction)
     at JetBrains.ReSharper.Psi.Caches.PsiCaches.Update()
     at JetBrains.ReSharper.Psi.Caches.PsiCaches.<.ctor>b__0(IPsiTransaction transaction)
     at JetBrains.ReSharper.Psi.Transactions.PsiTransactions.NotifyCommit(IPsiTransaction transaction)
”

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]
Message = “The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
Data.ManagedThreadName = <NULL>
Data.LastExtension = cs
Data.SccRevisionShell = “<there are no packages matching the criteria>”
Data.HostProductInfo = “JetBrains ReSharper Ultimate 2016.3.2  Build 107.0.20170126.120331”
Data.SubProducts.#0 = “JetBrains dotCover 2016.3.2 Build 2016.3.20170126.121718”
Data.SubProducts.#1 = “JetBrains dotTrace 2016.3.2 Build 2016.3.20170126.121657”
Data.SubProducts.#2 = “JetBrains ReSharper 2016.3.2 Build 2016.3.20170126.121504”
Data.SubProducts.#3 = “JetBrains dotMemory 2016.3.2 Build 2016.3.20170126.121625”
Data.SccRevisionEnv = “
  Platform\Core\Shell:
   git::refs/heads/wave07::2ac846a8af8df11aedd892dc2861143c2fd82dfc
  
  
  Platform\VisualStudio:
   git::refs/heads/wave07-2016-3-2-rtm::e9dedfa10637ebb870c2c1f53caaf745adc7a5e3
”
Data.VsVersion = 14.0.25431.1
InnerException = “Exception #1 at Root.InnerException”
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  at JetBrains.ReSharper.Psi.Transactions.PsiTransactions.NotifyCommit(IPsiTransaction transaction)
     at JetBrains.ReSharper.Psi.Transactions.PsiTransactions.CommitTransaction()
     at JetBrains.ReSharper.Psi.Transactions.PsiTransactionCookie.Commit()
     at JetBrains.ReSharper.Psi.Transactions.PsiTransactionCookie.ExecuteConditionally(IPsiServices psiServices, Func`1 action, String commandName)
     at JetBrains.ReSharper.Feature.Services.Refactorings.DrivenRefactoringConflictSearcher.SearchConflicts(IProgressIndicator pi, Boolean canPerformRefactoring)
     at JetBrains.ReSharper.Feature.Services.Refactorings.WorkflowExecuter.<>c__DisplayClass13.<InitPage>b__d(IProgressIndicator pi)
     at JetBrains.ReSharper.Feature.Services.Refactorings.FunctionWrapper`1.ExecuteAction(IProgressIndicator pi)
     at JetBrains.UI.Application.Progress.UITaskExecutorRun.RunStartTaskCallTaskAction(IProperty`1 isDone, ProgressIndicator progressIndicator, TaskThreadAffinity taskThreadAffinity, Action`1 FTask, JetDispatcher dispatcherPrimary)
     at JetBrains.UI.Application.Progress.UITaskExecutorRun.RunCore(TaskThreadAffinity taskThreadAffinity, Action`1 FTask, Func`3 FAttachUi, ProgressIndicator progressIndicator, IWin32Window parentWindow, IThreading threading, WorkerThreadShop workerThreadShop, Boolean enforceModalityState)
     at JetBrains.UI.Application.Progress.UITaskExecutorRun.Run(TaskThreadAffinity taskThreadAffinity, Action`1 task, Func`3 FAttachUi, ProgressIndicator indicator, IWin32Window parentWindow, IThreading threading, WorkerThreadShop workerThreadShop, Boolean enforceModalityState)
     at JetBrains.ReSharper.Feature.Services.Refactorings.RefactoringsTaskExecutor.JetBrains.Application.Progress.ITaskExecutor.ExecuteTask(String name, TaskCancelable cancelable, Action`1 task)
     at JetBrains.ReSharper.Feature.Services.Refactorings.WorkflowExecuter.RunWithProgress[TResult](Func`2 action, String taskName, TResult& result)
     at JetBrains.ReSharper.Feature.Services.Refactorings.WorkflowExecuter.InitPage(IRefactoringPage page)
     at JetBrains.ReSharper.Feature.Services.Refactorings.WorkflowExecuter.NextPage(IRefactoringPage currentPage)
     at JetBrains.ReSharper.Feature.Services.Refactorings.WorkflowExecuter.InitPage(IRefactoringPage page)
     at JetBrains.ReSharper.Feature.Services.Refactorings.WorkflowExecuter.NextPage(IRefactoringPage currentPage)
     at JetBrains.ReSharper.Feature.Services.Refactorings.WorkflowExecuter.InitPage(IRefactoringPage page)
     at JetBrains.ReSharper.Feature.Services.Refactorings.WorkflowExecuter.NextPage(IRefactoringPage currentPage)
     at JetBrains.ReSharper.Feature.Services.Refactorings.WorkflowExecuter.MoveToNextPage()
     at JetBrains.ReSharper.Feature.Services.Refactorings.WorkflowHostWithWizardForm.<NextClick>b__8()
     at JetBrains.Threading.ReentrancyGuard.Execute(String name, Action action)
     at JetBrains.Threading.ReentrancyGuard.ExecuteOrQueue(String name, Action action, TaskPriority priority)
     at JetBrains.ReSharper.Feature.Services.Refactorings.WorkflowHostWithWizardForm.NextClick(Object sender, EventArgs e)
     at JetBrains.ReSharper.Feature.Services.Refactorings.RefactoringWizardForm.myContinueButton_Click(Object sender, EventArgs e)
     at System.Windows.Forms.Control.OnClick(EventArgs e)
     at System.Windows.Forms.Button.OnClick(EventArgs e)
     at System.Windows.Forms.Button.PerformClick()
     at System.Windows.Forms.Form.ProcessDialogKey(Keys keyData)
     at System.Windows.Forms.Control.ProcessDialogKey(Keys keyData)
     at System.Windows.Forms.Control.ProcessDialogKey(Keys keyData)
     at System.Windows.Forms.Control.ProcessDialogKey(Keys keyData)
     at System.Windows.Forms.TextBoxBase.ProcessDialogKey(Keys keyData)
     at JetBrains.ReSharper.Feature.Services.UI.CompletionPicker.CompletionPickerEdit.ProcessDialogKey(Keys keyData)
     at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
     at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
     at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
     at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FPreTranslateMessage(MSG& msg)
     at System.Windows.Forms.ComponentManagerProxy.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FPreTranslateMessage(MSG& msg)
```

An excerpt from the Fusion log:
```
=== Pre-bind state information ===
LOG: DisplayName = NuGet.Core, Version=2.13.0.824, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = devenv.exe
Calling assembly : TestLinker, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
[...]
LOG: Attempting download of new URL file:///C:/Users/[...]/AppData/Local/JetBrains/Installations/ReSharperPlatformVs14/NuGet.Core.DLL.
LOG: Assembly download was successful. Attempting setup of file: C:\Users\[...]\AppData\Local\JetBrains\Installations\ReSharperPlatformVs14\NuGet.Core.dll
LOG: Entering run-from-source setup phase.
LOG: Assembly Name is: NuGet.Core, Version=2.14.0.832, Culture=neutral, PublicKeyToken=5aaa11a165479571
WRN: Comparing the assembly name resulted in the mismatch: Minor Version
ERR: The assembly reference did not match the assembly definition found.
ERR: Run-from-source setup phase failed with hr = 0x80131040.
LOG: Attempting download of new URL file:///C:/Users/[...]/AppData/Local/JetBrains/Installations/ReSharperPlatformVs14/NuGet.Core/NuGet.Core.DLL.
LOG: Attempting download of new URL file:///C:/Users/[...]/AppData/Local/JetBrains/Installations/ReSharperPlatformVs14/NuGet.Core.EXE.
LOG: Attempting download of new URL file:///C:/Users/[...]/AppData/Local/JetBrains/Installations/ReSharperPlatformVs14/NuGet.Core/NuGet.Core.EXE.
LOG: All probing URLs attempted and failed.
```

**Comment by matkoch** [comment]
Fixed.
